# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diameterdialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DiameterDialog(object):
    def setupUi(self, DiameterDialog):
        DiameterDialog.setObjectName("DiameterDialog")
        DiameterDialog.resize(587, 298)
        self.labelDiameter = QtWidgets.QLabel(DiameterDialog)
        self.labelDiameter.setGeometry(QtCore.QRect(358, 70, 201, 55))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelDiameter.setFont(font)
        self.labelDiameter.setObjectName("labelDiameter")
        self.widget = QtWidgets.QWidget(DiameterDialog)
        self.widget.setGeometry(QtCore.QRect(30, 30, 320, 191))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonZero = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonZero.sizePolicy().hasHeightForWidth())
        self.pushButtonZero.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonZero.setFont(font)
        self.pushButtonZero.setObjectName("pushButtonZero")
        self.gridLayout.addWidget(self.pushButtonZero, 2, 3, 1, 1)
        self.pushButtonEight = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonEight.sizePolicy().hasHeightForWidth())
        self.pushButtonEight.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonEight.setFont(font)
        self.pushButtonEight.setObjectName("pushButtonEight")
        self.gridLayout.addWidget(self.pushButtonEight, 2, 1, 1, 1)
        self.pushButtonFour = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonFour.sizePolicy().hasHeightForWidth())
        self.pushButtonFour.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonFour.setFont(font)
        self.pushButtonFour.setObjectName("pushButtonFour")
        self.gridLayout.addWidget(self.pushButtonFour, 1, 0, 1, 1)
        self.pushButtonThree = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonThree.sizePolicy().hasHeightForWidth())
        self.pushButtonThree.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonThree.setFont(font)
        self.pushButtonThree.setObjectName("pushButtonThree")
        self.gridLayout.addWidget(self.pushButtonThree, 0, 2, 1, 1)
        self.pushButtonOne = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonOne.sizePolicy().hasHeightForWidth())
        self.pushButtonOne.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonOne.setFont(font)
        self.pushButtonOne.setObjectName("pushButtonOne")
        self.gridLayout.addWidget(self.pushButtonOne, 0, 0, 1, 1)
        self.pushButtonSeven = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSeven.sizePolicy().hasHeightForWidth())
        self.pushButtonSeven.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonSeven.setFont(font)
        self.pushButtonSeven.setObjectName("pushButtonSeven")
        self.gridLayout.addWidget(self.pushButtonSeven, 2, 0, 1, 1)
        self.pushButtonTwo = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonTwo.sizePolicy().hasHeightForWidth())
        self.pushButtonTwo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonTwo.setFont(font)
        self.pushButtonTwo.setObjectName("pushButtonTwo")
        self.gridLayout.addWidget(self.pushButtonTwo, 0, 1, 1, 1)
        self.pushButtonSix = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSix.sizePolicy().hasHeightForWidth())
        self.pushButtonSix.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonSix.setFont(font)
        self.pushButtonSix.setObjectName("pushButtonSix")
        self.gridLayout.addWidget(self.pushButtonSix, 1, 2, 1, 1)
        self.pushButtonFive = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonFive.sizePolicy().hasHeightForWidth())
        self.pushButtonFive.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonFive.setFont(font)
        self.pushButtonFive.setObjectName("pushButtonFive")
        self.gridLayout.addWidget(self.pushButtonFive, 1, 1, 1, 1)
        self.pushButtonNine = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonNine.sizePolicy().hasHeightForWidth())
        self.pushButtonNine.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonNine.setFont(font)
        self.pushButtonNine.setObjectName("pushButtonNine")
        self.gridLayout.addWidget(self.pushButtonNine, 2, 2, 1, 1)
        self.pushButtonConform = QtWidgets.QPushButton(DiameterDialog)
        self.pushButtonConform.setGeometry(QtCore.QRect(170, 240, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonConform.setFont(font)
        self.pushButtonConform.setObjectName("pushButtonConform")
        self.pushButtonDeleteNumber = QtWidgets.QPushButton(DiameterDialog)
        self.pushButtonDeleteNumber.setGeometry(QtCore.QRect(340, 240, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonDeleteNumber.setFont(font)
        self.pushButtonDeleteNumber.setObjectName("pushButtonDeleteNumber")
        self.pushButtonBack = QtWidgets.QPushButton(DiameterDialog)
        self.pushButtonBack.setGeometry(QtCore.QRect(30, 240, 111, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonBack.sizePolicy().hasHeightForWidth())
        self.pushButtonBack.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonBack.setFont(font)
        self.pushButtonBack.setObjectName("pushButtonBack")

        self.retranslateUi(DiameterDialog)
        QtCore.QMetaObject.connectSlotsByName(DiameterDialog)

    def retranslateUi(self, DiameterDialog):
        _translate = QtCore.QCoreApplication.translate
        DiameterDialog.setWindowTitle(_translate("DiameterDialog", "Diameter Dialog"))
        self.labelDiameter.setText(_translate("DiameterDialog", "=36cm diameter"))
        self.pushButtonZero.setText(_translate("DiameterDialog", "0"))
        self.pushButtonEight.setText(_translate("DiameterDialog", "8"))
        self.pushButtonFour.setText(_translate("DiameterDialog", "4"))
        self.pushButtonThree.setText(_translate("DiameterDialog", "3"))
        self.pushButtonOne.setText(_translate("DiameterDialog", "1"))
        self.pushButtonSeven.setText(_translate("DiameterDialog", "7"))
        self.pushButtonTwo.setText(_translate("DiameterDialog", "2"))
        self.pushButtonSix.setText(_translate("DiameterDialog", "6"))
        self.pushButtonFive.setText(_translate("DiameterDialog", "5"))
        self.pushButtonNine.setText(_translate("DiameterDialog", "9"))
        self.pushButtonConform.setText(_translate("DiameterDialog", "Conform"))
        self.pushButtonDeleteNumber.setText(_translate("DiameterDialog", "Delete number"))
        self.pushButtonBack.setText(_translate("DiameterDialog", "back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DiameterDialog = QtWidgets.QDialog()
    ui = Ui_DiameterDialog()
    ui.setupUi(DiameterDialog)
    DiameterDialog.show()
    sys.exit(app.exec_())

