# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'treetypedialogex.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TreeTypeDialogEx(object):
    def setupUi(self, TreeTypeDialogEx):
        TreeTypeDialogEx.setObjectName("TreeTypeDialogEx")
        TreeTypeDialogEx.resize(497, 179)
        self.verticalLayout = QtWidgets.QVBoxLayout(TreeTypeDialogEx)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonBirke = QtWidgets.QPushButton(TreeTypeDialogEx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonBirke.sizePolicy().hasHeightForWidth())
        self.pushButtonBirke.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonBirke.setFont(font)
        self.pushButtonBirke.setObjectName("pushButtonBirke")
        self.gridLayout.addWidget(self.pushButtonBirke, 0, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        self.pushButtonApfel = QtWidgets.QPushButton(TreeTypeDialogEx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonApfel.sizePolicy().hasHeightForWidth())
        self.pushButtonApfel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonApfel.setFont(font)
        self.pushButtonApfel.setObjectName("pushButtonApfel")
        self.gridLayout.addWidget(self.pushButtonApfel, 0, 3, 1, 1)
        self.pushButtonBuche = QtWidgets.QPushButton(TreeTypeDialogEx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonBuche.sizePolicy().hasHeightForWidth())
        self.pushButtonBuche.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonBuche.setFont(font)
        self.pushButtonBuche.setObjectName("pushButtonBuche")
        self.gridLayout.addWidget(self.pushButtonBuche, 0, 5, 1, 1)
        self.pushButtonAhorn = QtWidgets.QPushButton(TreeTypeDialogEx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAhorn.sizePolicy().hasHeightForWidth())
        self.pushButtonAhorn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonAhorn.setFont(font)
        self.pushButtonAhorn.setObjectName("pushButtonAhorn")
        self.gridLayout.addWidget(self.pushButtonAhorn, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.pushButtonErle = QtWidgets.QPushButton(TreeTypeDialogEx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonErle.sizePolicy().hasHeightForWidth())
        self.pushButtonErle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonErle.setFont(font)
        self.pushButtonErle.setObjectName("pushButtonErle")
        self.gridLayout.addWidget(self.pushButtonErle, 1, 3, 1, 1)
        self.pushButtonEiche = QtWidgets.QPushButton(TreeTypeDialogEx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonEiche.sizePolicy().hasHeightForWidth())
        self.pushButtonEiche.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonEiche.setFont(font)
        self.pushButtonEiche.setObjectName("pushButtonEiche")
        self.gridLayout.addWidget(self.pushButtonEiche, 1, 2, 1, 1)
        self.pushButtonCancel = QtWidgets.QPushButton(TreeTypeDialogEx)
        self.pushButtonCancel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonCancel.sizePolicy().hasHeightForWidth())
        self.pushButtonCancel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonCancel.setFont(font)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.gridLayout.addWidget(self.pushButtonCancel, 2, 1, 1, 1)
        self.pushButtonEsche = QtWidgets.QPushButton(TreeTypeDialogEx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonEsche.sizePolicy().hasHeightForWidth())
        self.pushButtonEsche.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonEsche.setFont(font)
        self.pushButtonEsche.setObjectName("pushButtonEsche")
        self.gridLayout.addWidget(self.pushButtonEsche, 1, 4, 1, 1)
        self.pushButtonFichte = QtWidgets.QPushButton(TreeTypeDialogEx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonFichte.sizePolicy().hasHeightForWidth())
        self.pushButtonFichte.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonFichte.setFont(font)
        self.pushButtonFichte.setObjectName("pushButtonFichte")
        self.gridLayout.addWidget(self.pushButtonFichte, 1, 5, 1, 1)
        self.pushButtonKiefer = QtWidgets.QPushButton(TreeTypeDialogEx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonKiefer.sizePolicy().hasHeightForWidth())
        self.pushButtonKiefer.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonKiefer.setFont(font)
        self.pushButtonKiefer.setObjectName("pushButtonKiefer")
        self.gridLayout.addWidget(self.pushButtonKiefer, 2, 2, 1, 1)
        self.pushButtonKirsche = QtWidgets.QPushButton(TreeTypeDialogEx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonKirsche.sizePolicy().hasHeightForWidth())
        self.pushButtonKirsche.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonKirsche.setFont(font)
        self.pushButtonKirsche.setObjectName("pushButtonKirsche")
        self.gridLayout.addWidget(self.pushButtonKirsche, 2, 3, 1, 1)
        self.pushButtonLinde = QtWidgets.QPushButton(TreeTypeDialogEx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonLinde.sizePolicy().hasHeightForWidth())
        self.pushButtonLinde.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonLinde.setFont(font)
        self.pushButtonLinde.setObjectName("pushButtonLinde")
        self.gridLayout.addWidget(self.pushButtonLinde, 2, 4, 1, 1)
        self.pushButtonPappel = QtWidgets.QPushButton(TreeTypeDialogEx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonPappel.sizePolicy().hasHeightForWidth())
        self.pushButtonPappel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonPappel.setFont(font)
        self.pushButtonPappel.setObjectName("pushButtonPappel")
        self.gridLayout.addWidget(self.pushButtonPappel, 2, 5, 1, 1)
        self.pushButtonTanne = QtWidgets.QPushButton(TreeTypeDialogEx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonTanne.sizePolicy().hasHeightForWidth())
        self.pushButtonTanne.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonTanne.setFont(font)
        self.pushButtonTanne.setObjectName("pushButtonTanne")
        self.gridLayout.addWidget(self.pushButtonTanne, 3, 2, 1, 1)
        self.pushButtonWeide = QtWidgets.QPushButton(TreeTypeDialogEx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonWeide.sizePolicy().hasHeightForWidth())
        self.pushButtonWeide.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonWeide.setFont(font)
        self.pushButtonWeide.setObjectName("pushButtonWeide")
        self.gridLayout.addWidget(self.pushButtonWeide, 3, 3, 1, 1)
        self.pushButtonPlaceh1 = QtWidgets.QPushButton(TreeTypeDialogEx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonPlaceh1.sizePolicy().hasHeightForWidth())
        self.pushButtonPlaceh1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonPlaceh1.setFont(font)
        self.pushButtonPlaceh1.setObjectName("pushButtonPlaceh1")
        self.gridLayout.addWidget(self.pushButtonPlaceh1, 3, 4, 1, 1)
        self.pushButtonPlaceh3 = QtWidgets.QPushButton(TreeTypeDialogEx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonPlaceh3.sizePolicy().hasHeightForWidth())
        self.pushButtonPlaceh3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonPlaceh3.setFont(font)
        self.pushButtonPlaceh3.setObjectName("pushButtonPlaceh3")
        self.gridLayout.addWidget(self.pushButtonPlaceh3, 4, 2, 1, 1)
        self.pushButtonPlaceh2 = QtWidgets.QPushButton(TreeTypeDialogEx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonPlaceh2.sizePolicy().hasHeightForWidth())
        self.pushButtonPlaceh2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonPlaceh2.setFont(font)
        self.pushButtonPlaceh2.setObjectName("pushButtonPlaceh2")
        self.gridLayout.addWidget(self.pushButtonPlaceh2, 3, 5, 1, 1)
        self.pushButtonBestandsbaum = QtWidgets.QPushButton(TreeTypeDialogEx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonBestandsbaum.sizePolicy().hasHeightForWidth())
        self.pushButtonBestandsbaum.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonBestandsbaum.setFont(font)
        self.pushButtonBestandsbaum.setObjectName("pushButtonBestandsbaum")
        self.gridLayout.addWidget(self.pushButtonBestandsbaum, 4, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(TreeTypeDialogEx)
        QtCore.QMetaObject.connectSlotsByName(TreeTypeDialogEx)

    def retranslateUi(self, TreeTypeDialogEx):
        _translate = QtCore.QCoreApplication.translate
        TreeTypeDialogEx.setWindowTitle(_translate("TreeTypeDialogEx", "Tree Type Dialog"))
        self.pushButtonBirke.setText(_translate("TreeTypeDialogEx", "Birke"))
        self.pushButtonApfel.setText(_translate("TreeTypeDialogEx", "Apfel"))
        self.pushButtonBuche.setText(_translate("TreeTypeDialogEx", "Buche"))
        self.pushButtonAhorn.setText(_translate("TreeTypeDialogEx", "Ahorn"))
        self.pushButtonErle.setText(_translate("TreeTypeDialogEx", "Erle"))
        self.pushButtonEiche.setText(_translate("TreeTypeDialogEx", "Eiche"))
        self.pushButtonCancel.setText(_translate("TreeTypeDialogEx", "Cancel"))
        self.pushButtonEsche.setText(_translate("TreeTypeDialogEx", "Esche"))
        self.pushButtonFichte.setText(_translate("TreeTypeDialogEx", "Fichte"))
        self.pushButtonKiefer.setText(_translate("TreeTypeDialogEx", "Kiefer"))
        self.pushButtonKirsche.setText(_translate("TreeTypeDialogEx", "Kirsche"))
        self.pushButtonLinde.setText(_translate("TreeTypeDialogEx", "Linde"))
        self.pushButtonPappel.setText(_translate("TreeTypeDialogEx", "Pappel"))
        self.pushButtonTanne.setText(_translate("TreeTypeDialogEx", "Tanne"))
        self.pushButtonWeide.setText(_translate("TreeTypeDialogEx", "Weide"))
        self.pushButtonPlaceh1.setText(_translate("TreeTypeDialogEx", "Placeh1"))
        self.pushButtonPlaceh3.setText(_translate("TreeTypeDialogEx", "Placeh3"))
        self.pushButtonPlaceh2.setText(_translate("TreeTypeDialogEx", "Placeh2"))
        self.pushButtonBestandsbaum.setText(_translate("TreeTypeDialogEx", "Bestandsbaum"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TreeTypeDialogEx = QtWidgets.QDialog()
    ui = Ui_TreeTypeDialogEx()
    ui.setupUi(TreeTypeDialogEx)
    TreeTypeDialogEx.show()
    sys.exit(app.exec_())

