# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'treetypedialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TreeTypeDialog(object):
    def setupUi(self, TreeTypeDialog):
        TreeTypeDialog.setObjectName("TreeTypeDialog")
        TreeTypeDialog.resize(436, 226)
        self.gridLayout_2 = QtWidgets.QGridLayout(TreeTypeDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonLarch = QtWidgets.QPushButton(TreeTypeDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonLarch.sizePolicy().hasHeightForWidth())
        self.pushButtonLarch.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonLarch.setFont(font)
        self.pushButtonLarch.setObjectName("pushButtonLarch")
        self.gridLayout.addWidget(self.pushButtonLarch, 2, 5, 1, 1)
        self.pushButtonAlder = QtWidgets.QPushButton(TreeTypeDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAlder.sizePolicy().hasHeightForWidth())
        self.pushButtonAlder.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonAlder.setFont(font)
        self.pushButtonAlder.setObjectName("pushButtonAlder")
        self.gridLayout.addWidget(self.pushButtonAlder, 2, 4, 1, 1)
        self.pushButtonPoplar = QtWidgets.QPushButton(TreeTypeDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonPoplar.sizePolicy().hasHeightForWidth())
        self.pushButtonPoplar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonPoplar.setFont(font)
        self.pushButtonPoplar.setObjectName("pushButtonPoplar")
        self.gridLayout.addWidget(self.pushButtonPoplar, 2, 3, 1, 1)
        self.pushButtonAsh = QtWidgets.QPushButton(TreeTypeDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAsh.sizePolicy().hasHeightForWidth())
        self.pushButtonAsh.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonAsh.setFont(font)
        self.pushButtonAsh.setObjectName("pushButtonAsh")
        self.gridLayout.addWidget(self.pushButtonAsh, 1, 4, 1, 1)
        self.pushButtonSpruce = QtWidgets.QPushButton(TreeTypeDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSpruce.sizePolicy().hasHeightForWidth())
        self.pushButtonSpruce.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonSpruce.setFont(font)
        self.pushButtonSpruce.setObjectName("pushButtonSpruce")
        self.gridLayout.addWidget(self.pushButtonSpruce, 0, 3, 1, 1)
        self.pushButtonBeech = QtWidgets.QPushButton(TreeTypeDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonBeech.sizePolicy().hasHeightForWidth())
        self.pushButtonBeech.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonBeech.setFont(font)
        self.pushButtonBeech.setObjectName("pushButtonBeech")
        self.gridLayout.addWidget(self.pushButtonBeech, 1, 5, 1, 1)
        self.pushButtonPine = QtWidgets.QPushButton(TreeTypeDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonPine.sizePolicy().hasHeightForWidth())
        self.pushButtonPine.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonPine.setFont(font)
        self.pushButtonPine.setObjectName("pushButtonPine")
        self.gridLayout.addWidget(self.pushButtonPine, 0, 4, 1, 1)
        self.pushButtonOak = QtWidgets.QPushButton(TreeTypeDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonOak.sizePolicy().hasHeightForWidth())
        self.pushButtonOak.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonOak.setFont(font)
        self.pushButtonOak.setObjectName("pushButtonOak")
        self.gridLayout.addWidget(self.pushButtonOak, 1, 3, 1, 1)
        self.pushButtonBirch = QtWidgets.QPushButton(TreeTypeDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonBirch.sizePolicy().hasHeightForWidth())
        self.pushButtonBirch.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonBirch.setFont(font)
        self.pushButtonBirch.setObjectName("pushButtonBirch")
        self.gridLayout.addWidget(self.pushButtonBirch, 0, 5, 1, 1)
        self.pushButtonCancel = QtWidgets.QPushButton(TreeTypeDialog)
        self.pushButtonCancel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonCancel.sizePolicy().hasHeightForWidth())
        self.pushButtonCancel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonCancel.setFont(font)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.gridLayout.addWidget(self.pushButtonCancel, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(TreeTypeDialog)
        QtCore.QMetaObject.connectSlotsByName(TreeTypeDialog)

    def retranslateUi(self, TreeTypeDialog):
        _translate = QtCore.QCoreApplication.translate
        TreeTypeDialog.setWindowTitle(_translate("TreeTypeDialog", "Tree Type Dialog"))
        self.pushButtonLarch.setText(_translate("TreeTypeDialog", "Larch"))
        self.pushButtonAlder.setText(_translate("TreeTypeDialog", "Alder"))
        self.pushButtonPoplar.setText(_translate("TreeTypeDialog", "Poplar"))
        self.pushButtonAsh.setText(_translate("TreeTypeDialog", "Ash"))
        self.pushButtonSpruce.setText(_translate("TreeTypeDialog", "Spruce"))
        self.pushButtonBeech.setText(_translate("TreeTypeDialog", "Beech"))
        self.pushButtonPine.setText(_translate("TreeTypeDialog", "Pine"))
        self.pushButtonOak.setText(_translate("TreeTypeDialog", "Oak"))
        self.pushButtonBirch.setText(_translate("TreeTypeDialog", "Birch"))
        self.pushButtonCancel.setText(_translate("TreeTypeDialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TreeTypeDialog = QtWidgets.QDialog()
    ui = Ui_TreeTypeDialog()
    ui.setupUi(TreeTypeDialog)
    TreeTypeDialog.show()
    sys.exit(app.exec_())

